### ISSUE TITLE
移动端适配

### ISSUE THREAD

**Issue by gst-xxz** [gst-xxz/blog#30]
- https://juejin.cn/post/6844903845617729549#heading-26

**Comment by gst-xxz** [comment]
## 1px 边框
```js
.border-1 {
  position: relative;
  &::after {
    content: '';
    position: absolute;
    bottom: 0;
    left: 0;
    right: 0;
    width: 100%;
    height: 1px;
    background: black;
    transform-origin: 50% 0;
  }
}

@media only screen and(-webkit-min-device-pixel-ratio:2) {
  .border-1 {
    &::after {
      transform: scaleY(0.5);
    }
  }
}
@media only screen and(-webkit-min-device-pixel-ratio:3) {
  .border-1 {
    &::after {
      transform: scaleY(0.333);
    }
  }
}
```

**Comment by gst-xxz** [comment]
## flex

- [flex参考](https://www.ruanyifeng.com/blog/2015/07/flex-grammar.html)

```
// flex-grow flex-shrink flex-basic
flex: 1 1 auto;

// flex-grow属性定义项目的放大比例，默认为0，即如果存在剩余空间，也不放大。
// flex-shrink属性定义了项目的缩小比例，默认为1，即如果空间不足，该项目将缩小。
// flex-basis属性定义了在分配多余空间之前，项目占据的主轴空间（main size）。浏览器根据这个属性，计算主轴是否有多余空间。它的默认值为auto，即项目的本来大小。
```

**Comment by gst-xxz** [comment]
## 计算题
```
400 - (300 + 200) = -100 
300*2 + 200 *1 = 800

盒子left: 300 2
-100 * 2 * 300 / 800  = -75
300 + (-75) = 225

盒子right: 200 1
-100 * 1 * 200 / 800 = -25
200 + (-25) = 175
```

```css
.left {
  flex: 1 2 300px;
  /* flex-shrink: 2; */
  /* flex-basis: 300px; */
  height: 100px;
  background: red;
}

.right {
  flex: 2 1 200px;
  /* flex-shrink: 1; */
  /* flex-basis: 200px; */
  height: 100px;
  background: green;
}
```
